### ISSUE TITLE
Data for Database

### ISSUE THREAD

**Issue by katerinafig** [doganoo/audio-recognizer2#2]
Please, could you give database data(tables, keys and other)?

**Comment by doganoo** [comment]
actually not, I am sorry.

Just let the program run and record your audio/define an audio as your data source

**Comment by katerinafig** [comment]
Everything is fine, I already looked at the requests and on this data I created a database that works well, thanks! This is really cool application!

**Comment by doganoo** [comment]
nice. It helped me through my exam, hope it helps you too ✌️
